/**
 * Conversation logging for the KI Consult client portal.
 *
 * Writes with the Supabase secret key, which bypasses RLS — this module is
 * server-only and must never be imported from a client component.
 *
 * Every call is best-effort: logging is observability, not product. A failure
 * here (Supabase down, schema not applied, network blip) must never surface to
 * a customer mid-chat, so everything is swallowed and reported to the server
 * log only. Callers should `void` these promises rather than await them in the
 * request's critical path.
 */

const URL = process.env.SUPABASE_URL;
const KEY = process.env.SUPABASE_SECRET_KEY;
const SLUG = process.env.PORTAL_CLIENT_SLUG;

/** Logging stays off entirely unless all three are configured. */
export const loggingEnabled = Boolean(URL && KEY && SLUG);

function headers(extra: Record<string, string> = {}): Record<string, string> {
  return {
    apikey: KEY as string,
    Authorization: `Bearer ${KEY}`,
    "Content-Type": "application/json",
    ...extra,
  };
}

async function sb(path: string, init: RequestInit): Promise<Response> {
  const res = await fetch(`${URL}/rest/v1/${path}`, { ...init, cache: "no-store" });
  if (!res.ok) {
    throw new Error(`Supabase ${res.status}: ${(await res.text()).slice(0, 200)}`);
  }
  return res;
}

// The slug -> uuid mapping never changes for a deployment, so resolve once per
// warm instance instead of on every message.
let clientIdCache: string | null = null;

async function resolveClientId(): Promise<string> {
  if (clientIdCache) return clientIdCache;
  const res = await sb(
    `clients?slug=eq.${encodeURIComponent(SLUG as string)}&select=id`,
    { method: "GET", headers: headers() }
  );
  const rows = (await res.json()) as { id: string }[];
  if (!rows.length) throw new Error(`No clients row for slug "${SLUG}"`);
  clientIdCache = rows[0].id;
  return clientIdCache;
}

export type TurnUsage = {
  inputTokens: number;
  outputTokens: number;
  cacheCreationInputTokens: number;
  cacheReadInputTokens: number;
};

export type TurnLog = {
  /** Stable id for the whole chat session, generated by the browser. */
  conversationId: string;
  /** The customer's message that triggered this turn. */
  userMessage: string;
  /** The assistant's full reply text once streaming finished. */
  assistantMessage: string;
  /** True once a booking succeeded at any point in this conversation. */
  booked: boolean;
  /** Total messages in the session so far, for the portal's list view. */
  messageCount: number;
  /** Summed across every model call this turn made (tool-use rounds included). */
  usage: TurnUsage;
};

/**
 * Records one user/assistant exchange. Creates the conversation row on the
 * first turn and updates its counters on every turn.
 */
export async function logTurn(t: TurnLog): Promise<void> {
  if (!loggingEnabled) return;
  try {
    const clientId = await resolveClientId();

    // First turn creates the row; later turns collide on the primary key and
    // are ignored, so this stays a single round-trip either way.
    await sb("conversations", {
      method: "POST",
      headers: headers({ Prefer: "resolution=ignore-duplicates,return=minimal" }),
      body: JSON.stringify({ id: t.conversationId, client_id: clientId }),
    });

    // Every object in a PostgREST batch insert must carry the *same* keys —
    // a heterogeneous batch is rejected outright with PGRST102 ("All object
    // keys must match"), losing both rows. So the user row spells out the
    // token columns as null rather than omitting them: usage is a property of
    // the turn, and it's attributed to the single assistant row per turn,
    // matching how the chat route sums it across the agentic loop.
    const rows = [
      {
        conversation_id: t.conversationId,
        role: "user",
        content: t.userMessage,
        input_tokens: null,
        output_tokens: null,
        cache_creation_input_tokens: null,
        cache_read_input_tokens: null,
      },
      {
        conversation_id: t.conversationId,
        role: "assistant",
        content: t.assistantMessage,
        input_tokens: t.usage.inputTokens,
        output_tokens: t.usage.outputTokens,
        cache_creation_input_tokens: t.usage.cacheCreationInputTokens,
        cache_read_input_tokens: t.usage.cacheReadInputTokens,
      },
    ].filter((r) => r.content.trim().length > 0);

    if (rows.length) {
      await sb("messages", {
        method: "POST",
        headers: headers({ Prefer: "return=minimal" }),
        body: JSON.stringify(rows),
      });
    }

    // `booked` is sticky: only ever patch it to true, so a later non-booking
    // turn can't erase the fact that this conversation converted.
    const patch: Record<string, unknown> = {
      last_message_at: new Date().toISOString(),
      message_count: t.messageCount,
    };
    if (t.booked) patch.booked = true;

    await sb(`conversations?id=eq.${t.conversationId}`, {
      method: "PATCH",
      headers: headers({ Prefer: "return=minimal" }),
      body: JSON.stringify(patch),
    });
  } catch (err) {
    console.error("portal-log: failed to record turn:", err);
  }
}
