import { ImageResponse } from "next/og";
import { getAllPosts, getPost } from "@/lib/blog";

// Per-post OG image (1200x630), generated by Next at build time. Every post
// gets a unique branded share card - matters for CTR when links land in
// social feeds and chat apps, and doubles as the BlogPosting schema image.

export const size = { width: 1200, height: 630 };
export const contentType = "image/png";
export const alt = "KI Consult blogg";

export function generateStaticParams() {
  return getAllPosts().map((post) => ({ slug: post.slug }));
}

export default async function Image({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = getPost(slug);
  const title = post?.title ?? "KI Consult";
  const category = post?.category ?? "Blogg";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "64px 72px",
          background: "#0B2118",
          backgroundImage:
            "radial-gradient(900px 500px at 75% -10%, rgba(21,192,124,0.25), transparent 65%)",
          color: "#EFEDE2",
        }}
      >
        <div
          style={{
            display: "flex",
            fontSize: 26,
            letterSpacing: 6,
            color: "#3FE0A0",
            fontWeight: 700,
          }}
        >
          {`BLOGG / ${category.toUpperCase()}`}
        </div>
        <div
          style={{
            display: "flex",
            fontSize: title.length > 55 ? 62 : 72,
            fontWeight: 800,
            lineHeight: 1.12,
            letterSpacing: -2,
            maxWidth: 1020,
          }}
        >
          {title}
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <div style={{ display: "flex", fontSize: 34, fontWeight: 800 }}>KI Consult</div>
          <div style={{ display: "flex", fontSize: 34, fontWeight: 800, color: "#3FE0A0" }}>
            .no
          </div>
        </div>
      </div>
    ),
    size,
  );
}
